// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:587f1ab4-4d62-4e4d-9a50-96f5f763845f",
    "aws_cognito_region": "us-east-1",
    "aws_mobile_analytics_app_id": "5bf3dd8a2b1f427d8d12d5bb6b65908d",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
